-- In-tree fixtures.
-- Shared programs stay at `Examples.<Name>`; SVM-only programs live under `Examples.Svm`.
-- Lake also builds every file under `Examples/` via `globs`.

-- Shared (TokenShape is a transfer-shaped stub)
import Examples.Counter
import Examples.TokenShape
import Examples.Pair
import Examples.Flag
import Examples.Maybe
import Examples.Window
import Examples.Phase
import Examples.Lang

-- SVM
import Examples.Svm.Book
import Examples.Svm.Choice
import Examples.Svm.Clock
import Examples.Svm.Transfer
import Examples.Svm.Ping
import Examples.Svm.Call
import Examples.Svm.Info
import Examples.Svm.Peer
import Examples.Svm.Pda
import Examples.Svm.Signed
import Examples.Svm.Create
import Examples.Svm.TokenXfer
import Examples.Svm.Token2022
import Examples.Svm.Ata
import Examples.Svm.Rent
import Examples.Svm.TokenMint
import Examples.Svm.SysAlloc
import Examples.Svm.TokenAcc
import Examples.Svm.Memo
import Examples.Svm.CreatePda
import Examples.Svm.TokenApprove
import Examples.Svm.TokenFreeze
import Examples.Svm.TokenAuth
import Examples.Svm.Epoch
import Examples.Svm.TokenSize
import Examples.Svm.SysSeed
import Examples.Svm.SysXfer
import Examples.Svm.TokenMint2
import Examples.Svm.TokenNative
import Examples.Svm.Hash
import Examples.Svm.Keys
import Examples.Svm.Keccak
import Examples.Svm.Trio
import Examples.Svm.Gate
import Examples.Svm.Nonce
import Examples.Svm.TokenOwner
import Examples.Svm.TokenMs
import Examples.Svm.TokenStateView
import Examples.Svm.SelfLog
import Examples.Svm.BatchSizer
import Examples.Svm.Nested
import Examples.Svm.Seat
import Examples.Svm.Tree
import Examples.Svm.RawEntry
import Examples.Svm.JobQueue
import Examples.Svm.TicketLine
import Examples.Svm.FeatureBits
import Examples.Svm.ClaimBits
import Examples.Svm.MemberDirectory
import Examples.Svm.UniqueRoster
import Examples.Svm.VersionedLedger
import Examples.Svm.VersionedMigrator
import Examples.Svm.PhoenixV1Layout
import Examples.Svm.Phoenix
import Examples.Svm.PhoenixV1Profile
import Examples.Svm.AccountView
import Examples.Svm.MemoryOps
import Examples.Svm.TransientPair
import Examples.Svm.TransientLedger
import Examples.Svm.TransientOrderTape
import Examples.Svm.TransientWide128
import Examples.Svm.TransientWide256
import Examples.Svm.LamportTransfer
import Examples.Svm.PubkeyGate
import Examples.SvmExceptErgonomics
import Examples.Svm.AccountViewMutation
import Examples.Svm.InstructionsSlice
import Examples.Svm.MemoUtf8
import Examples.Svm.RentTopUp
import Examples.Svm.Token2022MintClose
import Examples.Svm.TransientPubkeyBatch
import Examples.Svm.TransientPubkeyRing
import Examples.Svm.HashWords
import Examples.Svm.TokenMintBurn
import Examples.Svm.TokenMultisig
import Examples.Svm.HashDataSha
import Examples.Svm.HashDataKeccak
import Examples.Svm.TokenSizeVerified
import Examples.Svm.Token2022SizeVerified
import Examples.Svm.VaultRentGrow
import Examples.Svm.VersionedPayloadMigrator

