import Tests.CounterSpec
import Tests.PairSpec
import Tests.FlagSpec
import Tests.WindowSpec
import Tests.BookSpec
import Tests.PhaseSpec
import Tests.ChoiceSpec
import Tests.ClockSpec
import Tests.TransferSpec
import Tests.PingSpec
import Tests.CallSpec
import Tests.InfoSpec
import Tests.PeerSpec
import Tests.PdaSpec
import Tests.SignedSpec
import Tests.CreateSpec
import Tests.TokenXferSpec
import Tests.Token2022Spec
import Tests.Token2022MintCloseSpec
import Tests.AtaSpec
import Tests.RentSpec
import Tests.TokenMintSpec
import Tests.SysAllocSpec
import Tests.TokenAccSpec
import Tests.MemoSpec
import Tests.MemoUtf8Spec
import Tests.CreatePdaSpec
import Tests.TokenApproveSpec
import Tests.TokenFreezeSpec
import Tests.TokenAuthSpec
import Tests.EpochSpec
import Tests.TokenSizeSpec
import Tests.SysSeedSpec
import Tests.SysXferSpec
import Tests.TokenMint2Spec
import Tests.TokenNativeSpec
import Tests.HashSpec
import Tests.KeysSpec
import Tests.KeccakSpec
import Tests.TrioSpec
import Tests.GateSpec
import Tests.NonceSpec
import Tests.TokenOwnerSpec
import Tests.TokenMsSpec
import Tests.SelfLogSpec
import Tests.CliSpec
import Tests.Fixtures
import Tests.ProfileSpec
import Tests.ExtractSpec
import Tests.EmitSpec
import Tests.BuildSpec
import Tests.LayoutSpec
import Tests.Sha256Spec
import Tests.CoreCodecSpec
import Tests.CoreCollectionsSpec
import Tests.SvmExceptErgonomicsSpec
import Tests.CoreMathSpec
import Tests.LangSpec
import Tests.IdlSpec
import Tests.DumpIncrement
import Tests.NormalizationSpec
import Tests.SolanalibSpec
import Tests.SolanalibSkipChainSpec
import Tests.TargetOpsSpec
import Tests.SvmHeapSpec
import Tests.SvmScratchSpec
import Tests.CFGSpec
import Tests.NestedSpec
import Tests.SeatSpec
import Tests.TreeSpec
import Tests.SvmSdkStorageSpec
import Tests.SvmSdkQueueSpec
import Tests.SvmSdkStorageBitSetSpec
import Tests.SvmSdkStorageEnumerableSetSpec
import Tests.SvmVersionedCodecSpec
import Tests.SvmSdkAccountSpec
import Tests.SvmTransientSpec
import Tests.SvmSdkPdaSystemSpec
import Tests.SvmSdkSystemSpec
import Tests.SvmSdkTokenSpec
import Tests.SvmSdkTokenStateSpec
import Tests.SvmSdkProgramSpec
import Tests.SvmSdkSysvarSpec
import Tests.InstructionsSliceSpec
import Tests.EntryAdapterSpec
import Tests.AccountViewSpec
import Tests.AccountViewMutationSpec
import Tests.RentTopUpSpec
import Tests.VaultRentGrowSpec
import Tests.OwnerReassignPolicySpec
import Tests.SvmMemorySpec
import Tests.SvmAccountResizeSpec
import Tests.SvmTransientVectorSpec
import Tests.SvmTransientBytesSpec
import Tests.SvmTransientRecordSpec
import Tests.SvmTransientWideVectorSpec
import Tests.SvmTransientPubkeyVectorSpec
import Tests.SvmTransientResourceManifestSpec
import Tests.SvmWideReturnSpec
import Tests.SvmTelemetrySpec
import Tests.LamportTransferSpec
import Tests.SvmSdkPubkeySpec
import Tests.TokenShapeSpec
import Tests.SvmReturnDataSpec
import Tests.SvmToken2022ExtSpec
import Tests.SvmHashWordsSpec
import Tests.ProofSpec
import Tests.SemanticsSpec
